server:
  port: "8080"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  name: "llm_cloud"

jwt:
  secret: "tjp020215"
  expiration_hours: 24

storage:
  type: "local" # 或 oss / minio
  local:
    base_dir: "./storage_data"
  oss:
    endpoint: ""
    bucket: ""
    access_key_id: ""
    access_key_secret: ""
  minio:
    endpoint: "localhost:9000"
    bucket: "llm-cloud"
    access_key_id: "minioadmin"
    access_key_secret: "minioadmin"
    use_ssl: false
    region: ""

# 新增 CORS 配置
cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: "12h" # 12 小时